spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOACK_JWK_SET_URL}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          lower-case-service-id: true
        httpclient:
        connect-timeout: 1000
        response-timeout: 10s

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8070/eureka

info:
  app:
    name: next-gen-gateway
    description: next-gen-gateway
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8081
