spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${UAMS_DB_HOST}:3306/next-gen-uams
    username: ${UAMS_DB_USER}
    password: ${UAMS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8070/eureka

info:
  app:
    name: next-gen-uams
    description: next-gen-uams
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
server:
  port: 8082

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

keycloak:
  client_id: next-gen-uams
  client_secret: ${NEXT_GEN_UAMS_CLIENT_SECRET}
  token_url: ${KEYCLOACK_TOKEN_URL}
  user_url: ${KEYCLOACK_USER_URL}

next:
  gen:
    kyc:
      output:
        consumer:
          group: "next-gen-kyc-output-consumer"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
